export const singleTools = [
  {
    slug: 'ahrefs-group-buy',
    title: 'Ahrefs Group Buy Cheap 100% Stable, Reliable, and Risk-Free',
    shortTitle: 'Ahrefs Group Buy',
    category: 'SEO TOOLS',
    image: '/assets/img/ahref1.png',
    price: '$10.00',
    original: '$119.00',
    blurb:
      'Grab the #1 SEO tool at an unbeatable cost. Unlimited credits per day, instant access, and 99.99% uptime.',
    details: [
      'Backlink index with historical data and link growth charts.',
      'Keyword Explorer for difficulty, clicks, and parent topics.',
      'Site Audit to catch technical SEO issues quickly.',
    ],
  },
  {
    slug: 'semrush-group-buy',
    title: 'Semrush Group Buy',
    shortTitle: 'Semrush Group Buy',
    category: 'SEO TOOLS',
    image: '/assets/img/sem.png',
    price: '$9.99',
    original: '$10.00',
    blurb:
      'Affordable Semrush group buy – Rank higher, grow faster! Unlimited access, one-click login, money-back guarantee.',
    details: [
      'Keyword Magic Tool for deep research and grouping.',
      'Domain Overview to compare competitors at a glance.',
      'Position tracking with daily SERP updates.',
    ],
  },
  {
    slug: 'envato-elements-group-buy',
    title: 'Envato Elements Group Buy',
    shortTitle: 'Envato Elements',
    category: 'Design / Assets',
    image: '/assets/img/env.png',
    price: '$5.00',
    original: '$10.00',
    blurb:
      'Affordable Envato Elements group buy – instant access to premium assets with money-back guarantee.',
  },
  {
    slug: 'grammarly-group-buy',
    title: 'Grammarly Group Buy – Premium Writing Tools',
    shortTitle: 'Grammarly',
    category: 'Writing Tools',
    image: '/assets/img/gr.png',
    price: '$4.99',
    original: '$10.00',
    blurb: 'Premium grammar and style checker access at a fraction of the price.',
    details: [
      'Advanced grammar and clarity suggestions.',
      'Tone detection for emails and long‑form content.',
      'Plagiarism checks against academic and web sources.',
    ],
  },
  {
    slug: 'kwfinder-group-buy',
    title: 'KWFinder Group Buy',
    shortTitle: 'KWFinder',
    category: 'SEO TOOLS',
    image: '/assets/img/kw.png',
    price: '$4.99',
    original: '$10.00',
    blurb: 'Easy long‑tail keyword research with accurate difficulty metrics.',
    details: [
      'Accurate KD for long‑tail topics and local SEO.',
      'Autocomplete and questions for content ideas.',
      'SERP overview with real competitors and metrics.',
    ],
  },
  {
    slug: 'majestic-group-buy',
    title: 'Majestic Group Buy',
    shortTitle: 'Majestic',
    category: 'SEO TOOLS',
    image: '/assets/img/mj.png',
    price: '$10.00',
    original: '$20.00',
    blurb: 'Backlink index and Trust Flow metrics at a low monthly price.',
    details: [
      'Trust Flow and Citation Flow scoring for link quality.',
      'Link Graph visualization to spot networks.',
      'Historic index to analyze past campaigns.',
    ],
  },
  {
    slug: 'frase-group-buy',
    title: 'Frase Group Buy – Instant Content Tool',
    shortTitle: 'Frase',
    category: 'SEO TOOLS',
    image: '/assets/img/fra.png',
    price: '$5.00',
    original: '$50.00',
    blurb: 'Outline, research, and optimize content with SERP-driven briefs.',
    details: [
      'Create SEO content briefs from top SERP competitors in seconds.',
      'AI writing assistance for outlines, headings, and sections.',
      'Built‑in content score to optimize coverage and readability.',
      'Answer engine to cluster questions and topics from search intent.',
    ],
  },
  {
    slug: 'netflix-group-buy',
    title: 'Netflix Group Buy',
    shortTitle: 'Netflix',
    category: 'Streaming',
    image: '/assets/img/net.png',
    price: '$5.00',
    original: '$10.00',
    blurb: 'Shared access with stable uptime and instant activation.',
  },
  {
    slug: 'prime-video-group-buy',
    title: 'Prime Video Group Buy',
    shortTitle: 'Prime Video',
    category: 'Streaming',
    image: '/assets/img/pr.png',
    price: '$3.00',
    original: '$10.00',
    blurb: 'Enjoy Prime Video content at ultra‑low shared prices.',
  },
  {
    slug: 'canva-group-buy',
    title: 'Best Canva Group Buy Deal – Full Pro Features at Just $1/Month',
    shortTitle: 'Canva Pro',
    category: 'SEO TOOLS',
    image: '/assets/img/canva.png',
    price: '$4.99',
    original: '$10.00',
    blurb: 'Full Pro features, templates, and brand kit access for less.',
  },
  {
    slug: 'adobe-stock-group-buy',
    title: 'Adobe Stock group buy Accounts – Shared & Private',
    shortTitle: 'Adobe Stock',
    category: 'Designing tools',
    image: '/assets/img/des.png',
    price: '$10.00',
    original: '$10.00',
    blurb: 'High‑quality stock photos and vectors on a shared plan.',
  },
  {
    slug: 'udemy-group-buy',
    title: 'Udemy Group Buy',
    shortTitle: 'Udemy',
    category: 'SEO TOOLS',
    image: '/assets/img/ud.png',
    price: '$4.99',
    original: '$10.00',
    blurb: 'Access premium Udemy courses at a fraction of the cost.',
  },
  {
    slug: 'coursera-group-buy',
    title: 'Coursera Group Buy',
    shortTitle: 'Coursera',
    category: 'online courses tools',
    image: '/assets/img/co.png',
    price: '$4.99',
    original: '$10.00',
    blurb: 'Top university courses and certificates for less.',
  },
  {
    slug: 'claude-ai-group-buy',
    title: 'Claude AI Group Buy: Affordable Access to Claude’s Advanced AI Technology',
    shortTitle: 'Claude AI',
    category: 'SEO TOOLS',
    image: '/assets/img/cl.png',
    price: '$4.99',
    original: '$10.00',
    blurb: 'Affordable access to Claude’s powerful AI for writing and analysis.',
  },
];

export const SIGNUP_URL = 'https://members.seotoolsgroupbuy.us/signup';


